version: "3.8"

services:
  frontend:
    build : ./frontend
    container_name: react-ui
    ports:
      - 5173:5173
    stdin_open : true
    tty : true
    depends_on:
      - backend 
    networks:
      - mern-networks

  backend :
    build: ./backend
    environment: 
      - PORT=
      - user= 
      - pass =
      - key_id= 
      - key_secret = 
      - JWT_SECRET=

    container_name: node-api
    restart : always
    ports:
      - 4000:4000
    depends_on:
      - database
    networks:
      - mern-networks
  
  database:
    image: mongo
    container_name: mongo-db
    ports:
      - 27017-27017
    volumes:
      - data-volume:/data/db
    networks:
      - mern-networks

volumes:
  data-volume:
    driver: local
    
          
networks:
  mern-networks:
    driver: bridge

    
